### ISSUE TITLE
issue on databricks

### ISSUE THREAD

**Issue by Arnold1** [lightbend/scala-logging#101]
Hi,

i run into the following issue when using scalalogging on databricks. any idea what it means and how to fix it?

i use scala_logging version 3.7.2
scala 2.11

```
java.lang.InstantiationError: com.typesafe.scalalogging.Logger
	at com.typesafe.scalalogging.Logger$.apply(Logger.scala:32)
	at com.typesafe.scalalogging.LazyLogging$class.logger(Logging.scala:28)
	at com.someOrg.Main$.logger$lzycompute(Main.scala:17)
	at com.someOrg.Main$.logger(Main.scala:17)
	at com.someOrg.Main$.doSpark(Main.scala:39)
	at linefc4399efb4de4685ab70d641c74f4ba441.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:66)
	at linefc4399efb4de4685ab70d641c74f4ba441.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:85)
	at linefc4399efb4de4685ab70d641c74f4ba441.$read$$iw$$iw$$iw$$iw.<init>(<console>:87)
	at linefc4399efb4de4685ab70d641c74f4ba441.$read$$iw$$iw$$iw.<init>(<console>:89)
	at linefc4399efb4de4685ab70d641c74f4ba441.$read$$iw$$iw.<init>(<console>:91)
	at linefc4399efb4de4685ab70d641c74f4ba441.$read$$iw.<init>(<console>:93)
	at linefc4399efb4de4685ab70d641c74f4ba441.$eval$.$print$lzycompute(<console>:7)
	at linefc4399efb4de4685ab70d641c74f4ba441.$eval$.$print(<console>:6)
```

**Comment by Adrian-Sanz-Alstom** [comment]
same problem here..

**Comment by Arnold1** [comment]
@Adrian-Sanz-Alstom i ended up to fix it as follows: 
i changed from:
```
compile "com.typesafe.scala-logging:scala-logging_2.11:3.7.2"
```
to:
```
compile "com.typesafe.scala-logging:scala-logging-slf4j_2.11:2.1.2"
```

than i changed from:
```
import com.typesafe.scalalogging.LazyLogging
```
to
```
import com.typesafe.scalalogging.slf4j.LazyLogging
```

let me know if the same works for you!?

**Comment by Adrian-Sanz-Alstom** [comment]
Not yet @Arnold1 , how did you implement? I made your code changes but it doesn't work for me...
Databricks says it doesn't recognize val logger = Logger("") but If I enclose 'logger' inside a class yes.
I just want to implement my logger in one method...

**Comment by Adrian-Sanz-Alstom** [comment]
@Arnold1  I've "made the trick" with the following statement:
`import com.typesafe.scalalogging.slf4j.LazyLogging
import com.typesafe.scalalogging.slf4j.Logger

val logger = com.typesafe.scalalogging.slf4j.Logger(org.slf4j.LoggerFactory getLogger "test")
logger.info("Heello")`

But the log doesn't appear in the databricks console. How is your set up?

**Comment by Arnold1** [comment]
what do you mean?

**Comment by jeff303** [comment]
`scala-logging-slf4j_2.11` is an older library that is no longer having new releases.  Everything seems to have moved to `scala-logging-2.11`.

**Comment by Arnold1** [comment]
good to know :D

**Comment by timo-aho** [comment]
I could not make the solutions work. So, I explained mine in here:
https://github.com/lightbend/scala-logging/issues/68
