### ISSUE TITLE
Help me Incorporate pos into scala-logging.

### ISSUE THREAD

**Issue by JohnReedLOL** [lightbend/scala-logging#132]
I wrote [this library](https://github.com/JohnReedLOL/pos/) which features [this macro](https://github.com/JohnReedLOL/pos/blob/a7bdbb0d4af80d1953b520f6fc05ef595178219a/src/main/scala/com/github/johnreedlol/package.scala#L105). It allows me to do this:

```
import com.github.johnreedlol._

logger.debug("foo" + pos())
```

Which will print:

`17:52:09.794 [main] DEBUG  Log - foo    at my.package.Main.main(Main.scala:8)`

Since it looks like a stack trace, my text editor will take me to that line in the source code. The only problem is that I have to add `+ pos()` to every log line, which is annoying.

How do I modify scala-logging so that I can just do: 

`logger.debug("foo")`

and get:

`17:52:09.794 [main] DEBUG  Log - foo    at my.package.Main.main(Main.scala:8)`?

**Comment by JohnReedLOL** [comment]
Actually, I think that maybe the best approach would be to provide pos() as an implicit, so that it can be passed to scala-logger similar to the way it is done with the sourcecode library. Do you think that this would be the right approach?
